version: "3"
services:
  initial_data_builder:
    build: "./"
    volumes:
      - ../webapp:/webapp
    command: "bash -c 'pip install -r requirements.txt && go get github.com/orisano/wayt && make chair_data estate_data'"
